name: user-statistician

on:
  schedule:
    - cron: '04 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: user-statistician
        uses: cicirello/user-statistician@v1.14.0
